### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by MicahZoltu** [simov/recursive-fs#1]
I came across this because I needed to delete a single directory as part of an NPM script and the next best available option is `rimraf` which has 10 dependencies (just to delete a folder?!).  At the moment, I am doing the following in my NPM script:
```
node -e \"require('recursive-fs').rmdirr(require('path').resolve('bundles'), ()=>{})\"
```
but it would be nice if instead I could just do:
```
recursive-delete bundles
```
where `recursive-delete` is a CLI tool exposed by `recursive-fs`.  The same thing would be useful for `cpdirr` so I can get rid of my dependency on `copyfiles` (which comes with a whopping 72 dependencies!) in another project.

**Comment by simov** [comment]
Implemented in #2
